src/client/__tests__/calculate-updates.spec.js, src/client/calculate-updates.js
Previously the update code would return a pending update if required
data was timed out, but still fresh. This is incorrect. This code
corrects that oversight and adds tests to verify.
To Test:
=> Correct timeout behavior, only when not fresh.

src/client/__tests__/calculate-updates.spec.js, src/client/__tests__/index.spec.js, src/client/__tests__/requirements.spec.js, src/client/calculate-updates.js, src/client/index.js, src/client/requirements.js
This corrects the component requirement mapping to use an array of
requirements for each component, which is what is expected from the
ApiClient. It adjust existing tests and adds two more to verify
functionality.
To Test:
=> Use arrays for component requirement sets.

src/client/__tests__/calculate-updates.spec.js, src/client/__tests__/index.spec.js, src/client/__tests__/requirements.spec.js, src/client/calculate-updates.js, src/client/index.js, src/client/requirements.js
The ApiClient class represents a given API site indexed by a key.
The key can be platform-dependent. On WordPress.com, for instance,
this would be a numeric siteId. On a normal wp-admin setup, it
would be the API of the site. For a Stripe API, it could be
production or test.
This PR does not do the actual API method calls, however. It leaves that for an upcoming PR.
To Test:
=> Add ApiClient class

src/client/__tests__/calculate-updates.spec.js, src/client/calculate-updates.js, src/client/index.js
This adds a min/max with defaults for the next update value.
It also fixes a couple small issues that were found when using with the
hello-world example.
To Test:
=> Add min/max to calculate updates next update value

src/api/__tests__/index.spec.js, src/api/index.js
This adds a class for each api that can be subclassed and the methods,
endpoints, and selectors defined that way. It gives a central place of
code that can aggregate clients for just that api.
This will replace the existing registry.
To Test:
=> Add an api class for better client aggregation.

src/client/__tests__/index.spec.js, src/client/index.js
This splits out the timer handling and ensures that all updates happen
through a timeout command instead of ever doing it directly. This helps
ensure that we don't block the main thread for too long and it also
ensures that we will update our state before each re-render.
To Test:
=> ApiClient Split out timer from requirement updates

src/client/__tests__/index.spec.js, src/client/index.js
This adds subscribe/unsubscribe functionality to the ApiClient so that
things like components can watch for changes on the client and update
accordingly.
To Test:
1. `npm test` and ensure all tests run successfully.
=> ApiClient: Add subscribe/unsubscribe

src/react-redux/__tests__/provider.spec.js, src/react-redux/provider.js
This replaces the existing registry code as it handles the list of apis
within its own state. It also takes care of updating each api state as
it changes, and passes on dispatching action creators for data
requested, data received, and error received.
To Test:
=> Provider: Add api support.

package.json, src/react-redux/__tests__/with-api-client.spec.js, src/react-redux/with-api-client.js
This adds the `withApiClient` higher order component which works much
like the Redux `connect` HOC. It connects a component to selectors for a
given API.
To Test:
=> with-api-client: Add HOC and test

examples/wp-rest-api/src/App.js, examples/wp-rest-api/src/create-store.js, examples/wp-rest-api/src/index.js, examples/wp-rest-api/src/reducer.js
This adds the redux and fresh-data providers and reducer to the example
application.
To Test:
2. `npm run build`
3. `cd examples/wp-rest-api`
4. `npm install`
5. `npm start`
7. After localhost:3000 comes up in browser, check Redux dev tools state for `freshData: {}`
=> examples/wp-rest-api: Add providers

examples/wp-rest-api/src/App.css, examples/wp-rest-api/src/App.js, examples/wp-rest-api/src/PostList.js, examples/wp-rest-api/src/RecentPosts.js, examples/wp-rest-api/src/SiteSelect.js, examples/wp-rest-api/src/test-wp-rest-api.js
This adds an application that looks up recent posts, in addition to
implementing at test api class for the WordPress REST API
To Test:
2. `npm run build`
3. `cd examples/wp-rest-api`
4. `npm install`
5. `npm start`
6. Browser will open to localhost:3000
7. Type in URL of any WordPress site with API running and hit <enter> or "Go!" button.
8. Observe page of posts listing in a table.
This example app is functional at this point, but could be improved. Some things I'm considering:
1. Removing the `Go!` button and just automatically trying the URL after the user stops typing.
2. Adding a "Checking http://myurl.com" label while it's verifying the URL goes to a WordPress site.
3. Adding page links and a per-page selector.
Known issue:
There's a promise timing out and throwing …
=> examples/wp-rest-api: Add application code

src/client/__tests__/index.spec.js, src/client/index.js
The timeout parameter was omitted for waitForData, causing the
timeoutPromise to prematurely resolve.
An extra test was added to verify the correct behavior of this code.
To Test:
2. `npm test` and ensure all tests pass.
Additional testing:
The `wp-rest-api` example can be run and the dev console before would have shown an unhandled promise rejection (the timeoutPromise). With this code, that rejection should not happen.
=> Fix timeout in waitForData

package-lock.json, package.json
This changes the prepack script to a prepublishOnly script because as
prepack, it was running on a dependency npm install.
It also updates the lockfile while we're at it.
=> Update packages and prepublishOnly script

README.md, examples/hello-world/src/Message.js, examples/wp-rest-api/src/PostList.js, src/react-redux/__tests__/with-api-client.spec.js, src/react-redux/with-api-client.js
Originally, mapApiToProps actually passed down the apiClient object, but
since it's been simplified to only pass down selectors, the name of the
callback function should be changed as well.
To Test:
2. `npm run test`
=> withApiClient: Rename mapApiToProps

README.md, examples/hello-world/src/Message.js, examples/wp-rest-api/src/PostList.js, src/react-redux/__tests__/with-api-client.spec.js, src/react-redux/with-api-client.js
This adds an options parameter to withApiClient designed to hold
parameters that will be optional, like mapSelectorsToProps,
getClientKey, and the upcoming mapMutationsToProps.
It also helps keep things straight by mentioning them by name instead of
parameter order.
To Test:
2. `npm test`
Optional testing:
Run the examples and make sure they still work.
=> withApiClient: Add options parameter

README.md, src/api/__tests__/index.spec.js, src/api/index.js, src/client/__tests__/index.spec.js, src/client/index.js, src/react-redux/__tests__/with-api-client.spec.js, src/react-redux/with-api-client.js
This adds mutations to the api as a set of purpose-made mutations for
applications to use to send mutating operations to an API.
To Test:
2. `npm test`
No example code for testing mutations yet, but I'll be adding it to the wp plugin example next.
=> FreshDataApi: Add mutations

src/client/__tests__/index.spec.js, src/client/index.js
This pre-maps the operations so it only has to be done once.
This also ensures that all operations go through `applyOperation` and
not just `read`
To Test:
2. `npm test` and ensure all tests pass.
Optional additional testing is to run the example programs. (make sure to do `npm link` and `npm link fresh-data`
=> Pre-map api operations in client constructor

examples/hello-world/package-lock.json, examples/hello-world/package.json, examples/wp-rest-api/package-lock.json, examples/wp-rest-api/package.json
This updates the example apps to use the npm released code. No more `npm link` or `github:` required.
=> examples: Update to use 0.1.0 release

README.md, src/client/__tests__/index.spec.js, src/client/index.js
Addresses #65 
This changes `getData` to `getResource`, to return the entire resource state. This allows selectors access to metadata like `lastReceived`, `lastRequested`, `lastError`, and `error`.
It also changes `requireData` to `requireResource` to match, and `requireResource` also returns the resource state, just like `getResource` to save a line of code in selectors.
This PR also adds some more tests around these two functions for added coverage.
To Test:
1. `npm install`, `npm test` and ensure all tests pass.
=> Change getData/requireData to getResource/requireResource

README.md, src/api/__tests__/index.spec.js, src/api/index.js, src/client/__tests__/index.spec.js, src/react-redux/__tests__/with-api-client.spec.js
Addresses #69 
This moves `methods`, `operations`, `mutations`, and `selectors` from
static class members to instance members passed via the base class
constructor.
It will allow the `this` context to be used for these functions, and it
will also allow different `methods` to be passed in for different
instances of apis, which will prove valuable when running in different
environments.
Note that most of the line changes are in the tests. These don't need to be scrutinized much as long as the tests still run successfully.
To Test:
1. `npm install`, `npm test` and ensure all tests pass.
Additional testing for this PR can be done by following the test instructions in #73
=> Move static api members to instances

examples/hello-world/src/test-api.js, examples/wp-rest-api/src/PostList.js, examples/wp-rest-api/src/test-wp-rest-api.js, src/api/__tests__/index.spec.js, src/api/index.js, src/client/__tests__/index.spec.js, src/client/index.js
This PR updates the behavior around applying operations and promises. The goal of it is to return promises from operations and therefore be able to use these promises to resolve success/fail behavior in mutations. This will allow notifications and resolving interim optimistic states.
To Test:
2. `npm test`
There will be more testing in the application use of this after it is merged.
=> API and Client promise updates

examples/hello-world/src/test-api.js, examples/wp-rest-api/src/test-wp-rest-api.js
This updates the example code to the upcoming 0.2.0 release.
Required changes are:
1. `getData`/`requireData` -> `getResource`/`requireResource`
2. `methods`, `operations`, `mutations`, `selectors` no longer static
To Test:
0. `npm install`, `npm run build`, `npm link`
1. cd to `examples/hello-world`, `npm install`, `npm link @fresh-data/framework`, `npm start`
2. cd to `examples/wp-rest-api`, `npm install`, `npm link @fresh-data/framework`, `npm start`
=> Update examples to 0.2.0

examples/wp-rest-api/src/test-wp-rest-api.js
This adds a "loading" render state to the page loads.
=> Add a "loading" render to wp-rest-api example

src/api/__tests__/index.spec.js, src/api/index.js, src/client/__tests__/index.spec.js, src/client/index.js, src/react-redux/__tests__/actions.spec.js, src/react-redux/__tests__/provider.spec.js, src/react-redux/__tests__/with-api-client.spec.js, src/react-redux/actions.js, src/react-redux/provider.js, src/react-redux/reducer/__tests__/index.spec.js, src/react-redux/reducer/index.js, src/react-redux/with-api-client.js
This removes clientKey altogether from the api and associated code. The
clientKey can be directly associated with an instance of the API, we
don't need to keep multiple clients for the same instance. We can just
create multiple instances of the same API.
To Test:
1. `npm install`, `npm test` and ensure all tests pass.
For further cumulative testing of this and associated PRs, visit #81
=> Remove clientKey

src/client/__tests__/index.spec.js, src/client/index.js, src/react-redux/__tests__/with-api-client.spec.js
This removes the methods because the operations can be pre-loaded with
them when the apiSpec is created.
To Test:
1. `npm install`, `npm test` and ensure all tests pass.
Further testing can be done via PR #81
=> Remove methods from apiSpec.

examples/hello-world/package-lock.json, examples/hello-world/package.json, examples/hello-world/src/App.js, examples/hello-world/src/Message.js, examples/hello-world/src/index.js, examples/hello-world/src/test-api.js, examples/wp-rest-api/package-lock.json, examples/wp-rest-api/package.json, examples/wp-rest-api/src/App.js, examples/wp-rest-api/src/PostList.js, examples/wp-rest-api/src/SiteSelect.js, examples/wp-rest-api/src/http-fetch.js, examples/wp-rest-api/src/index.js, examples/wp-rest-api/src/test-wp-rest-api.js
This updates the example code to work with the following changes:
* #80 : Simplified provider that only holds a single api.
To Test:
0. `npm install`, `npm run build`, `npm link`.
For `examples/hello-world` and `examples/wp-rest-api`:
1. cd to example/xxx directory
2. `npm install`, `npm link @fresh-data/framework`, `npm start`
3. Verify operation of each example after it loads from `localhost:3000`
=> Update examples for upcoming 0.3.0

packages/react-provider/package.json
This updates the peer dependency, which didn't get updated automatically by lerna.
No testing needed.
=> build: Fix react-provider peer dependency

package.json
This adds a `linkLocal` script that can be used to link local packages
together without trying to hoist packages, which can be problematic for
example code that relies on `react-scripts` for binary access (which
hoisting thwarts)
It also fixes a previous `test:watch` script where `lerna` got
accidentally switched to `npm` which caused this script to not work.
=> Fix package.json test script and lerna link

packages/react-provider/src/provider.js
This component was ignoring changes to the children prop, which was
causing children to not update correctly.
Nothing to test here directly, but check out the github-example PR to test the results of this.
=> react-provider: Fix child updates

examples/github-api/src/UserInfo.js, examples/github-api/src/UserStars.js, packages/framework/src/client/index.js
This adds piecemeal methods for getting, setting, and clearing component
requirements instead of this only being done via a callback approach as
is used in `setComponentData`. This makes the client more compatible
with other systems that cannot provide callback support in this way.
=> Add methods for component requirements

packages/framework/src/client/__tests__/index.spec.js, packages/framework/src/client/index.js
The ApiClient code was using Map.clear() instead of Map.delete() which
was deleting all entries from the Map instead of just the one desired.
Tests were added to exhibit this behavior and to verify the fix.
To Test:
3. `npm test` and ensure all tests run successfully.
=> client: Fix the clearing of component requiremens.

examples/github-api/package-lock.json, examples/github-api/src/api-spec/github-rest-api.js, examples/github-api/src/index.js, examples/hello-world/package-lock.json, examples/hello-world/src/index.js, examples/hello-world/src/test-api.js, examples/wp-rest-api/package-lock.json, examples/wp-rest-api/src/index.js, examples/wp-rest-api/src/test-wp-rest-api.js, packages/framework/package-lock.json, packages/react-provider/package-lock.json
This adds devinfo and names to the example app api specs
To Test:
1. `npm install`, `npm run bootstrap`
2. For each example dir: `npm install`, `npm start`, ensure app runs, check dev console for `freshData.xxx` dev info in JS console.
=> Add devinfo to example apps

packages/framework/src/client/__tests__/resource-request.spec.js, packages/framework/src/client/resource-request.js, packages/framework/src/utils/__tests__/dates.spec.js, packages/framework/src/utils/dates.js
Partially addresses #203 
This is Step 1 of the Render-based refactor. It involves creating a new ResourceRequest class to track individual requests of resource keys. Note that this is a theoretical request and not necessarily 1:1 for network requests. A single network request can fulfill more than one resource request. In that case, multiple ResourceRequest objects will have references to the same request promise.
In this step, no actual behavior of the framework is changed. This only adds the ResourceRequest and corresponding tests.
To Test:
3. `npm run lint`
4. `npm run test`
=> Render-based refactor: Step 1

packages/framework/package-lock.json, packages/framework/src/client/__tests__/scheduler.spec.js, packages/framework/src/client/resource-request.js, packages/framework/src/client/scheduler.js, packages/react-provider/package-lock.json
Partially addresses #203
In step 2 of the refactor, a Scheduler class is created to manage the resource requests that come from the requirements of the components. This part is used to de-dupe resource needs, and ensure that all components are represented in the current set of requests. This is how it is no longer needed to keep track of the requirements of each component.
To Test:
3. `npm run lint`
4. `npm run test`
=> Render-based refactor: Step 2

packages/framework/src/client/__tests__/resource-request.spec.js, packages/framework/src/client/__tests__/scheduler.spec.js, packages/framework/src/client/resource-request.js, packages/framework/src/client/scheduler.js
Partially addresses #203 
Add operations to scheduler and requests
This allows all operations to be scheduled instead of just read
operations. This will allow the possibility of batched requests for all
operation types. Another functional benefit of this approach is that all API operations are in one place and easier to track/debug.
To Test:
3. `npm run lint`
4. `npm run test`
=> Render-based refactor: Step 3

packages/framework/src/devinfo/__tests__/index.spec.js, packages/framework/src/devinfo/index.js
Partially addresses #203 
This updates the devinfo with a link to the scheduler requests queue. The requests themselves have enough information in them to be useful from the console without further extra parsing. Note that this will essentially allow requests to be modified from the command line when devinfo is enabled.
To Test:
3. `npm run lint`
4. `npm run test`
To view in the browser JS console using the wp-rest-api example:
3. `npm run build`
4. `cd packages/react-provider; rm -rf node_modules/react-redux; cd ../../` (this fixes a quirky module conflict)
5. `cd examples/wp-rest-api`
6. `npm start`
Pro tip: In the browser console type `localStorage.setItem( 'debug', 'fresh-data:*' );` to see the debug …
=> Render-based refactor: Step 5

packages/framework/src/client/__tests__/index.spec.js, packages/framework/src/client/index.js, packages/framework/src/client/scheduler.js, packages/react-provider/src/__tests__/provider.spec.js
Fixes #233 
This fixes the problem where resources were getting fetched twice
because of the way react-redux connect works with rendering components
and sending out redux store subscriptions.
Disclaimer: This fix is a bit hacky to get around an issue we're having with redux where reducers are processed before subscribers to the redux store. I've been thinking of removing redux completely from fresh-data as a dependency and this is pushing me more in that direction.
To Test:
3. `npm run build`
4. `rm -rf packages/react-provider/node_modules/react-redux` (necessary because of local linking issues)
5. `cd examples/wp-rest-api`
6. `npm start`
After this, you should be able to observe only one initial fetch instead of two when using the code on master. …
=> Fix resources fetching twice

packages/framework/src/client/__tests__/index.spec.js, packages/framework/src/client/index.js
This stops the scheduler when the document is no longer visible, and
restarts it when the scheduler becomes visible again.
To Test:
1. Run any example application
2. Open dev console and run `localStorage.setItem( 'debug', 'fresh-data:*' );`
3. Switch to another tab or minimize browser.
4. Verify the debug states the scheduler is stopped and no more updates occur.
5. Switch back to example app tab and ensure scheduler restarts and fetches when necessary.
=> Add scheduler handling for document visibility

packages/framework/src/client/index.js
The implementation of withSelect used in woocommerce-admin and
woocommerce-payments wasn't registering the updated state, which was
causing reqduests to not be scheduled when they needed to bo.
This fixes it by ensuring that 	isClientStateInSync is updated before
subscription callbacks are fired.
To Test:
Just run the example apps to ensure use, and then symlink the framework directory into woocommerce-admin node_modules to test there.
=> Fix isClientStateInSync for withSelect
