Automattic/fresh-data

src/registry/__tests__/index.spec.js
src/registry/index.js
src/utils/__tests__/is-api-valid.spec.js
src/utils/is-api-valid.js

This adds the registerApi function along with validation and tests.
To Test:

Add registerApi function

---

src/client/__tests__/require-data.spec.js
src/client/__tests__/requirements.spec.js
src/client/require-data.js

This function is what selectors will use to set data requirements for a
given component.
To Test:

Add requireData utility function.

---

src/client/__tests__/calculate-updates.spec.js
src/client/__tests__/index.spec.js
src/client/__tests__/requirements.spec.js
src/client/calculate-updates.js
src/client/index.js
src/client/requirements.js

This adds code to check for state or requirements changes, but only
trigger an update when they've actually changed.
To Test:

Trigger update upon state or requirements change.

---

package-lock.json
package.json

This adds redux and react-redux as package dependencies.
To Test:
1. `npm install`.
2. Ensure `node_modules/redux` exists.
3. Ensure `node_modules/react-redux` exists.

Add redux to package.json

---

examples/hello-world/package-lock.json
examples/hello-world/package.json
examples/hello-world/src/App.js
examples/hello-world/src/App.test.js
examples/hello-world/src/Message.js
examples/hello-world/src/create-store.js
examples/hello-world/src/index.js
examples/hello-world/src/reducer.js

This adds redux to the hello-world example in preparation of the next step, which is using fresh-data in the example here.
To Test:
1. `cd examples/hello-world`
2. `npm start`
3. Visit `http://localhost:3000/` and ensure page loads and says "Hello World!"
4. Observe redux dev tools to ensure "World" is in state.

Add redux to hello-world example

---

src/client/__tests__/index.spec.js
src/client/index.js

This adds code that calls the connected api endpoint read methods from
ApiClient.fetchData.
To Test:

Add ApiClient.fetchData implementation

---

src/react-redux/__tests__/provider.spec.js
src/react-redux/provider.js

This provides the api state from within the redux state.
To Test:

Add a redux api state provider.

---

src/react-redux/reducer/__tests__/index.spec.js
src/react-redux/reducer/index.js

This adds the main reducer for fresh-data's redux implementation.
It sorts data by `[ apiName, clientKey ]`
To Test:
1. Run `npm test` and ensure all tests pass.

Add index reducer

---

examples/hello-world/package-lock.json
examples/hello-world/package.json
package-lock.json
package.json

This just updates the dependencies and makes sure tests still run fine.
To Test:
2. `npm test`

Update npm dependencies as of 5/25/2018

---

src/client/__tests__/index.spec.js
src/client/index.js

This updates the tests with the new API class.
To Test:

ApiClient: Use new api class for tests.

---

src/client/__tests__/index.spec.js
src/client/index.js

waitForData uses JS Promises to wait asynchronously for data, with a
built-in timeout.
To Test:

ApiClient: Add waitForData

---

package-lock.json
package.json

This allows react components to be tested.
To Test:
Test using PR #38

Add enzyme to package.json for react testing

---

src/index.js

This adds content to the src/index.js which is the public API for
fresh-data.
Nothing to test here. #27 can be used to test this.

Add public API index.

---

examples/hello-world/src/App.js
examples/hello-world/src/Message.js
examples/hello-world/src/reducer.js
examples/hello-world/src/test-api.js

The `hello-world` example is a basic example of the capabilities of `fresh-data`.
`hello-world` has a test API that returns a promise to simulate asynchronous requests. It has one API endpoint, `greetings`, which returns an array of "Hello world" in up to 27 languages. The first time the API GET request happens, it returns 1 string in the array. The second time, it returns 2 strings, and so on until it reaches 27 requests where it returns the entire array each time.
The `hello-world` Message component utilizes the `withClientApi` HOC to get the `greetings` data from the API and keep it current to every 10 seconds. (This means every 10 seconds, the component gets an extra language string in the array.) It then cycles through each string in the array every second.
The result is, the first …

Add fresh-data implementation for hello-world example

---

README.md

This adds instructions and explanations to the README file.
Nothing to test here, just review the [README](https://github.com/coderkevin/fresh-data/blob/59497eabd4c5888150bfedf22ff3bda8159d636e/README.md).
(Note: This is the same README as in #1, but that PR branch had continuing build issues, so this is to start over fresh.)

README: Add instructions

---

src/client/index.js

This collapses 4 functions into one which partially fulfills a curried
api function into one that is mapped to a client.
To Test:
2. `npm test` and ensure all tests pass.
This is a simple refactoring, so tests should be sufficient to ensure operation.

DRY client mapping functions.

---

README.md

Operations instead of endpoints now, and update the text on mutations.

This updates the README for operations

---

examples/hello-world/package-lock.json
examples/hello-world/package.json
examples/wp-rest-api/package-lock.json
examples/wp-rest-api/package.json

This updates the examples to 0.2.0.

Update examples package versions to 0.2.0

---

examples/hello-world/package-lock.json
examples/wp-rest-api/package-lock.json
examples/wp-rest-api/package.json
package-lock.json
package.json

Just updating packages for the project and examples.

Update packages as of July 28

---

packages/framework/package.json
packages/react-provider/package.json

This re-adds lint and test scripts just for the purpose of pre-publish
to make sure there are no problems.
Nothing to test here, this was already used to publish 0.3.0

packages: update npm scripts for publish

---

examples/hello-world/package-lock.json
examples/hello-world/package.json
examples/hello-world/src/App.js
examples/hello-world/src/Message.js
examples/hello-world/src/reducer.js
examples/wp-rest-api/package-lock.json
examples/wp-rest-api/package.json
examples/wp-rest-api/src/PostList.js
examples/wp-rest-api/src/SiteSelect.js
examples/wp-rest-api/src/reducer.js
lerna.json

This updates the examples to use the split out
@fresh-data/react-provider package, and places them
under the packages directory so lerna can link to them.
To Test:
0. `npm install`, `npm run bootstrap`
In both `examples/hello-world` and `examples/wp-rest-api`
1. `npm install`, `npm start`
2. Ensure example application works as expected.

Examples: Move to packages/ and update.

---

packages/framework/README.md
packages/react-provider/README.md

This updates the readme example code and creates readmes for each package.

Docs: Update readmes for 0.3.0

---

.travis.yml
examples/hello-world/package.json
examples/wp-rest-api/package.json
lerna.json
package-lock.json
package.json

This fixes the lerna json build by excluding the examples from lerna run
commands
To Test:
2. `npm run build-ci`

Fix lerna json build

---

.eslintrc.js
examples/hello-world/package-lock.json
examples/wp-rest-api/package-lock.json
package-lock.json
package.json
packages/framework/package-lock.json
packages/react-provider/package-lock.json
packages/react-provider/src/provider.js

This removes packages from the root package.json that are only needed by
example code.

examples: remove packages from root

---

examples/github-api/package-lock.json
examples/github-api/package.json
examples/hello-world/package-lock.json
examples/hello-world/package.json
examples/wp-rest-api/package-lock.json
examples/wp-rest-api/package.json
package-lock.json
package.json
packages/framework/package-lock.json
packages/framework/package.json
packages/react-provider/package-lock.json
packages/react-provider/package.json

This updates package dependencies for security fixes, etc.

Update package dependencies

---

README.md

I updated the README docs with:
- a section on adding fresh data to the redux state tree
- explicit list of steps that need to be taken to get fresh-data to work from scratch in a project (the steps were already there - now they're numbered, and under one section)
- `apiName` in the code snippets
I noticed there are some parts of the apiSpec that aren't used (e.g. `const thingNumber = resourceName.substr( resourceName.indexOf( ':' ) + 1 );`) but that can be taken care of in another iteration
Let me know if some things are off, happy to change as needed :)

Update README with steps to use

---

examples/github-api/package-lock.json
examples/hello-world/package-lock.json
examples/wp-rest-api/package-lock.json
package-lock.json
packages/framework/package-lock.json
packages/react-provider/package-lock.json
packages/react-provider/package.json

This updates package.lock files across the board.
Nothing needed for review here, just build to verify.
To Test:
Just run the steps in the `.travis.yml` file to ensure a local build.
Optional: Test example apps.

Update package.lock files

---

examples/github-api/package-lock.json
examples/hello-world/package-lock.json
examples/wp-rest-api/package-lock.json
package-lock.json
packages/framework/package-lock.json
packages/react-provider/package-lock.json

This just updates package-lock files. No additional testing other than CI tests are needed.

Update package-lock files
